language: python
python:
- 2.7
- 3.5
services:
- postgresql
addons:
  postgresql: '9.4'
install:
- pip install tox
before_script:
- psql -c "CREATE DATABASE dts_test_project;" -U postgres
script:
- tox -e py${TRAVIS_PYTHON_VERSION/./}-dj${DJANGO/./}
env:
- DJANGO=1.8
- DJANGO=1.9
- DJANGO=1.10
deploy:
  provider: pypi
  user: bcarneiro
  password:
    secure: BqLMnjgq+LWIDp1QymMiA4NCN2OdH20EGnQyI5lO/zR5Bo9NRu/vH0PIuYej7V+Sy7RR/AbuBlBmsfqcAqn60lggJevklOImqsJoxjPCcLPa99ICHXAMRIHothqqM7n062ki2uqQfcLMI2j5hTKe8safZAfvnhQnN5y8gXc6WZ5TMDutPeeFnQVkTUHYzQb3xcIO0fK2cSXHbOu0f+TrB9/LZccgAefFxa6LYo9ec+BRMP48t0P3zKjWG7UDJTCyQ/T+nw0nW9vfQrOqorZMH6vtjcIPptEx+E0BvU3v2pEKGdsIg197dK7MVXSIX5ctAPzl6VO/zV+TEpkagYHA1M0MCneoJfXIaUxj0yh4F0lPJB/aQGkrKd/Y2/QcPkhosgCgIjtdQYLrkvOg09tGMSeDQSoLsqxZeRlgsHHPgtiMGLa1bTyt4iUi+Iv9NlfJP2rpyOzvpOYfMgXYFWaxMz60y81u7yOqEHCF+Y23jUs9xmZkY1aD45AM+qodHQ6E3sLL9SaE+p9yfXXlySex94b8wyEksbUSK7FukR0gv7yQKSKOWbe32yWu81owDoBNpumHJmoeE/fe8XC8XltJeuenqVFBUGH0Zx+SiJVKj0pZDWeYV0WpsN22wfYrnTB5S7BFoaxrGRR4p+CIuoxH6mG3lF/5uWHvy62hZykC8Vs=
  on:
    distributions: sdist bdist_wheel
    repo: bernardopires/django-tenant-schemas
