language: python
python:
- 2.7
- 3.5
services:
- postgresql
addons:
  postgresql: '9.4'
install:
- pip install tox
before_script:
- psql -c "CREATE DATABASE dts_test_project;" -U postgres
script:
- tox -e py${TRAVIS_PYTHON_VERSION/./}-dj${DJANGO/./}
env:
- DJANGO=1.8
- DJANGO=1.9
- DJANGO=1.10
deploy:
  provider: pypi
  user: bcarneiro
  password:
    secure: DAx2Go/rcYusHZm1XrGPkZI6FLaWGcgqcmhjqy18Uj4+Wp23pSrkEsS/ERk7ImdRIHZBS1FDLNuJ7qF9ynJckaShF8y8z3lKk70sYQsbe3HKTNXjeKktOMRlOJqG6yHFpZG0LbT2mN1ucyq1FntoY2pIODySy+ZNBcNNbj5AYjGLQafWU+o3qzqcn+n6nGn7znclSBhAyasyFQWoFcuacwMJYA9YG/nOQ3fxB6lLSIORt6gpzTQ/OwbF6UasCkhfCLdjL8S8UM3CemHPcRox+bW0pevo1rGj1K0Cnw+0oynj+96wAinda0wrF3dtKgUSl2vnBN8laccazZir1qjTvVVXc1ggwHg0OJ/03uqDcoXk4tsopSbm5mGTtG4zS/rIt44qEU7Sgs6EzR0XME9Wenxka4Jq7k6BnFzNUqyXjrigWB2brCOH82VQIkbCrqX+AmAXVKIkJhaXM86V3MkRSeKaaE3yE1iLjyNpJsB3BZKgoVH7f+Etboadk4gzc6Di+xAPdYcAexgaCUHulGSU4IaJ/dd+6zjtlQUDG8rnUAGsRanRoYhYH1tsuxVKi/hUfUyv+AcUiEwaEUaH9i7q5xcJFyL8AI/nlU+fkkECQ/V6pPLdA8S/mO/SsQX9MMUvfcml3ucSALJKPUnAn1Nt8i41/tu0AJ2gLieV7RwbPOc=
